#!/bin/bash
# Generated by Copilot

# 配置路径
GLOBAL_PACKAGES_PATH="$HOME/.nuget/packages"
PROJECT_ASSETS_FILE="obj/project.assets.json"
OUTPUT_DIR="./ExtractedPackages"

# 创建输出目录
mkdir -p "$OUTPUT_DIR"

# 检查 project.assets.json 是否存在
if [ ! -f "$PROJECT_ASSETS_FILE" ]; then
    echo "Error: $PROJECT_ASSETS_FILE not found"
    exit 1
fi

# 使用 jq 解析 project.assets.json
# 如果没有安装 jq, 需要先安装: sudo apt-get install jq
if ! command -v jq &> /dev/null; then
    echo "Error: jq is required but not installed. Please install it first."
    echo "For Debian/Ubuntu: sudo apt-get install jq"
    echo "For Fedora: sudo dnf install jq"
    echo "For CentOS/RHEL: sudo yum install jq"
    exit 1
fi

# 提取包名和版本
echo "Extracting package information..."
jq -r '.libraries | to_entries[] | select(.value.type == "package") | .key' "$PROJECT_ASSETS_FILE" > /tmp/package_list.txt

# 复制包
while IFS= read -r pkg_full_name; do
    pkg_name=$(echo "$pkg_full_name" | cut -d'/' -f1 | tr '[:upper:]' '[:lower:]')
    pkg_version=$(echo "$pkg_full_name" | cut -d'/' -f2)
    
    source_path="$GLOBAL_PACKAGES_PATH/$pkg_name/$pkg_version"
    dest_path="$OUTPUT_DIR/$pkg_name/$pkg_version"
    
    if [ -d "$source_path" ]; then
        echo "Copying $pkg_full_name ..."
        mkdir -p "$dest_path"
        cp -r "$source_path"/* "$dest_path"
    else
        echo "Warning: Package not found: $pkg_full_name"
    fi
done < /tmp/package_list.txt

# 清理临时文件
rm -f /tmp/package_list.txt

echo "Extracted packages saved to: $OUTPUT_DIR"